version: '3.8'
services:
  redis-server:
    image: "redis:4-alpine3.8"
    ports:
      - "6379:6379"
  redis-server-second-api:
    image: "redis:4-alpine3.8"
    ports:
      - "6380:6379"
  redis-insight:
    image: "redislabs/redisinsight:latest"
    ports:
      - "8100:8001"
    volumes:
      - ./redisinsight:/db
  plantuml:
    image: plantuml/plantuml-server:tomcat
    ports:
      - "8888:8080"
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9001:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zoo1:2181
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://kafka-schema-registry:8081
    depends_on:
      - kafka1
      - kafka-schema-registry
      - zoo1